require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BbsController do

  # This should return the minimal set of attributes required to create a valid
  # Bb. As you add validations to Bb, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BbsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bbs as @bbs" do
      bb = Bb.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bbs).should eq([bb])
    end
  end

  describe "GET show" do
    it "assigns the requested bb as @bb" do
      bb = Bb.create! valid_attributes
      get :show, {:id => bb.to_param}, valid_session
      assigns(:bb).should eq(bb)
    end
  end

  describe "GET new" do
    it "assigns a new bb as @bb" do
      get :new, {}, valid_session
      assigns(:bb).should be_a_new(Bb)
    end
  end

  describe "GET edit" do
    it "assigns the requested bb as @bb" do
      bb = Bb.create! valid_attributes
      get :edit, {:id => bb.to_param}, valid_session
      assigns(:bb).should eq(bb)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bb" do
        expect {
          post :create, {:bb => valid_attributes}, valid_session
        }.to change(Bb, :count).by(1)
      end

      it "assigns a newly created bb as @bb" do
        post :create, {:bb => valid_attributes}, valid_session
        assigns(:bb).should be_a(Bb)
        assigns(:bb).should be_persisted
      end

      it "redirects to the created bb" do
        post :create, {:bb => valid_attributes}, valid_session
        response.should redirect_to(Bb.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bb as @bb" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bb.any_instance.stub(:save).and_return(false)
        post :create, {:bb => {}}, valid_session
        assigns(:bb).should be_a_new(Bb)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bb.any_instance.stub(:save).and_return(false)
        post :create, {:bb => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bb" do
        bb = Bb.create! valid_attributes
        # Assuming there are no other bbs in the database, this
        # specifies that the Bb created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bb.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bb.to_param, :bb => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bb as @bb" do
        bb = Bb.create! valid_attributes
        put :update, {:id => bb.to_param, :bb => valid_attributes}, valid_session
        assigns(:bb).should eq(bb)
      end

      it "redirects to the bb" do
        bb = Bb.create! valid_attributes
        put :update, {:id => bb.to_param, :bb => valid_attributes}, valid_session
        response.should redirect_to(bb)
      end
    end

    describe "with invalid params" do
      it "assigns the bb as @bb" do
        bb = Bb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bb.any_instance.stub(:save).and_return(false)
        put :update, {:id => bb.to_param, :bb => {}}, valid_session
        assigns(:bb).should eq(bb)
      end

      it "re-renders the 'edit' template" do
        bb = Bb.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bb.any_instance.stub(:save).and_return(false)
        put :update, {:id => bb.to_param, :bb => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bb" do
      bb = Bb.create! valid_attributes
      expect {
        delete :destroy, {:id => bb.to_param}, valid_session
      }.to change(Bb, :count).by(-1)
    end

    it "redirects to the bbs list" do
      bb = Bb.create! valid_attributes
      delete :destroy, {:id => bb.to_param}, valid_session
      response.should redirect_to(bbs_url)
    end
  end

end
